- name: Check for installed apps(virtualbox)
  shell: brew cask list | grep -c -v virtualbox
  register: app_installed
  changed_when: app_installed.stdout == 1

- name: install cask virtualbox
  shell: brew cask install virtualbox
  when:  app_installed.stdout == 1
